package hotels;

import java.io.IOException;
import java.net.URL;
import java.util.HashMap;
import java.util.Map;

import javax.net.ssl.HttpsURLConnection;

import org.testng.annotations.BeforeSuite;

import io.restassured.RestAssured;

public class GetSignature {
	public static String apiKey = "8yvm7h3ryzmn4me6pa8s4hq2";
	public static String Secret = "cT5yFbRRFk";
	public static String signature;
	public static String hotelName, roomMinRate, roomMaxRate,rateType,rateKey,bookingRef;;
	public static Map<String, Object> headerMap = new HashMap<String, Object>();

	@BeforeSuite
	public void createSigature() throws IOException {

		try {
			
			// Signature is generated by SHA256 (Api-Key + Secret +
			// Timestamp (in seconds))
			signature = org.apache.commons.codec.digest.DigestUtils
					.sha256Hex(apiKey + Secret + System.currentTimeMillis() / 1000);
			RestAssured.baseURI = "https://api.test.hotelbeds.com/hotel-api/1.0/";
			
			System.out.println(signature);

			headerMap.put("Api-key", apiKey);
			headerMap.put("X-Signature", signature);
			headerMap.put("Accept", "application/json");
			headerMap.put("Accept-Encoding", "gzip");
			headerMap.put("Content-Type", "application/json");

		} catch (Exception e) {
			e.printStackTrace();
		}

	}

}
